package com.auralink.creation.provider;

public enum ProviderErrorCategory {
   PROVIDER_FEATURE_DISABLED,
   PROVIDER_CONFIGURATION_MISSING,
   PROVIDER_CONFIGURATION_INVALID,
   PROVIDER_UNAVAILABLE,
   PROVIDER_TIMEOUT,
   PROVIDER_RATE_LIMITED,
   PROVIDER_REJECTED,
   PROVIDER_INVALID_RESPONSE,
   PROVIDER_OUTPUT_INVALID,
   PROVIDER_CAPACITY_EXCEEDED,
   PROVIDER_INTERNAL_CONTRACT_ERROR;
}
